# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

BOX = "bento/ubuntu-16.04"
NODES = 3

Vagrant.configure("2") do |config|
    (1..NODES).each do |i|
        config.vm.define "zk#{i}" do |subconfig|
            subconfig.vm.box = BOX
            subconfig.vm.hostname = "zk#{i}"
            subconfig.vm.network :private_network, ip: "10.0.0.#{i + 100}"
        end
    end

    config.vm.provision "shell", path: "provision/setup.sh"
end
